export const SPRITE_SIZE = 16;
export const TILE_SCALE = 4;

export const CONFIG = {
    spriteSize: SPRITE_SIZE,
    tileScale: TILE_SCALE,
    tileWidth: SPRITE_SIZE * TILE_SCALE,
    lakeWidth: 4,
    lakeHeight: 3,
    regionSize: 32,
    treeRegionSize: 16,
    INVENTORY_COLS: 4,
    INVENTORY_ROWS: 6,
    MAX_STACK: 64,
    INVENTORY_TEXT_SCALE: 0.9,
    ITEM_IMAGE_PATH: "assets/ui/items/",
    moveSpeed: 128,
    animInterval: 180,
    useDuration: 500,
    useCooldown: 500,
    CHOP_USES_REQUIRED: 4,
    CHOP_REWARD: "oak_log_chunk",
    CHOP_REWARD_COUNT: 4,
    GROUND_ITEM_SCALE: 2,
    GROUND_ITEM_BASE_SIZE: 16,
    GROUND_ITEM_BOB_AMPLITUDE: 4,
    DROP_DISTANCE: Math.round(SPRITE_SIZE * TILE_SCALE * 0.8),
    UPDATE_SEND_INTERVAL: 80,
    JOYSTICK_DEADZONE: 14,
    defaultCharacter: "assets/characters/basicrobot",
    directions: ["idle", "forward", "backward", "left", "right", "idleforward", "idlebackward", "idleleft", "idleright", "forwarduse", "backwarduse", "leftuse", "rightuse"],
    TILE_TYPES: ["grass", "water", "oak_log", "oak_tree_leaves"],
};

export const INVENTORY_SIZE = CONFIG.INVENTORY_COLS * CONFIG.INVENTORY_ROWS;

export const state = {
    characterPath: CONFIG.defaultCharacter,
    playerInventory: Array(INVENTORY_SIZE).fill(null),
    inventoryVisible: false,
    inventoryEl: null,
    cursorItem: null,
    cursorItemEl: null,
    tooltipEl: null,
    slotElements: [],
    touchDrag: null,
    isTouching: false,

    seed: [],
    playerWorldX: 0,
    playerWorldY: 0,
    direction: "idle",
    lastDirection: "backward",
    animFrame: 0,
    animTimer: 0,
    using: false,
    useTimer: 0,
    useCooldownTimer: 0,
    lastTime: 0,

    viewportEl: null,
    appEl: null,
    GAME_W: 0,
    GAME_H: 0,
    baselineDPR: 1,
    lastAppTransform: "",
    scaleX: 1,
    scaleY: 1,
    cameraX: 0,
    cameraY: 0,
    worldEl: null,
    playerEl: null,
    playerImgEl: null,
    drawnPlayerSrc: null,
    remotePlayerImgs: new Map(),
    drawnRemoteSrc: new Map(),
    coordEl: null,

    ws: null,
    localPlayerId: null,
    lastSentSnapshot: null,
    lastUpdateSentAt: 0,

    initStarted: false,
    gameLoopStarted: false,
    loadStatusEl: null,
    onGameConnected: null,

    joystickEl: null,
    joystickKnobEl: null,
    joystickTouchId: null,
    joystickCenterX: 0,
    joystickCenterY: 0,
    joystickRadius: 52,

    keys: {},
    imageCache: {},
    characterFrames: {},
    preloadedCharacters: new Set(),
    tileElements: new Map(),
    tileColors: {},
    spriteDataUrls: new Map(),
    remotePlayers: new Map(),
    remoteTargets: new Map(),
    remoteAnim: new Map(),
    removedTrees: new Set(),
    treeUseCounts: new Map(),
    groundItems: [],
    groundItemEls: new Map(),
    pendingPickups: new Set(),
};
